version: '3.7'

services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    restart: always
    ports:
      - '127.0.0.1:8080:8080'
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${CADDY_DATA_FOLDER}:/data