---
openapi: 3.0.0
info:
  title: Data Elements
  description: Initial draft for Data Elements in Workflow BB
  contact:
    email: aarelaponin@gmail.com
  license:
    name: MIT
  version: 1.0.0-oas3-oas3
servers:
  - url: https://virtserver.swaggerhub.com/DigitalImpactAllianc/Registration/1.0.0
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /process:
    get:
      tags:
        - developers
      summary: returns data about a process
      description: |
        Pass in the ID of the process and it will return all information about that process
      operationId: getProcess
      parameters:
        - name: processId
          in: query
          description: pass the unique identifier of the process
          required: true
          style: form
          explode: true
          schema:
            type: integer
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Process'
        "404":
          description: process not found
    post:
      tags:
        - admins
      summary: adds a process
      description: Adds a process to the system
      operationId: addProcess
components:
  schemas:
    Process:
      type: object
      properties:
        id:
          type: integer
          description: generated by a system surrogate primary key
        name:
          type: string
          description: name of a process
        type:
          type: string
          enum:
            - None
            - Private
            - Public
        isExecutable:
          type: boolean
          description: Specifies whether the Process is executable
        isClosed:
          type: boolean
          description: whether Messages and Events, not modeled in Process, can occur when the Process is executed or performed
        resources:
          $ref: '#/components/schema/ResourceRole'
        version:
          type: string
        description:
          type: string
    ResourceRole:
      type: object
      properties:
        id:
          type: integer
          description: generated by a system surrogate primary key
        resourceRef:
          type: integer
          description: reference to the Resource that is associated with Activity
    ProcessInstance:
      type: object
      properties:
        id:
          type: integer
          description: generated by a system surrogate primary key
        processRef:
          type: integer
          description: refrence to the process
        initTime:
          type: string
          description: Initiation Timestamp
        state:
          type: string
          description: see BPMN specification v.2.0 section 13.2.2
        lastChangeTime:
          type: string
          description: last change Timestamp
    Activity:
      type: object
      properties:
        id:
          type: integer
          description: generated by a system surrogate primary key
        isScript:
          type: boolean
        name:
          type: string
        categoryValueRef:
          type: integer
          description: A reference to the Category Values that are associated with this Flow Element
        isForCompensation:
          type: boolean
          description: A flag that identifies whether this Activity is intended for the purposes of compensation
        loopCharacteristics:
          $ref: '#/components/schemas/LoopCharacteristics'
        resources:
          items:
            $ref: '#/components/schemas/ResourceRole'
        default:
          $ref: '#/components/schemas/SequenceFlow'
        ioSpecification:
          $ref: '#/components/schemas/IoSpecification'
        startQuantity:
          type: integer
          description: number of tokens that must arrive before the activity can begin. Minamal value is 1
        completionQuantity:
          type: integer
          description: number of tokens to be generated from the activity; must not be less than 1
    ActivityInstance:
      type: object
      properties:
        id:
          type: integer
          description: generated by a system surrogate primary key
        activityRef:
          type: integer
          description: refrence to the process
        state:
          type: string
          description: see BPMN specification v.2.0 section 13.2.2
    LoopCharacteristics:
      type: object
      properties:
        id:
          type: integer
    SequenceFlow:
      type: object
      properties:
        id:
          type: integer
    IoSpecification:
      type: object
      properties:
        id:
          type: integer

