# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  bb-example-testing:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:18.10.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout

      - run: node --version
      - run: corepack enable

      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.12

      - run: cd test && pip install -r requirements.txt

      - run:
          name: 'Intro'
          command:
            'echo testing all examples in /examples against test suite in /test'

      # - run:
      #     name: 'Test n8n deployment via docker and a GovStack adaptor'
      #     command: 'cd examples/n8n && ./test_entrypoint.sh'

      # - run:
      #     name: 'Shut down n8n'
      #     command: 'cd examples/n8n && docker compose down'

      # - run:
      #     name:
      #       'Test OpenFn/Lightning deployment via docker and a GovStack adaptor'
      #     command: 'cd examples/lightning && ./test_entrypoint.sh'

      # - run:
      #     name: 'Shut down OpenFn/Lightning'
      #     command: 'cd examples/lightning && docker compose down'

      - run:
          name: 'Test Camunda deployment via docker and a GovStack adaptor'
          command: 'cd examples/camunda && ./test_entrypoint.sh'

      - run:
          name: 'Run cucumber tests against camunda image'
          command: cd test && yarn install && yarn run test

      - run:
          name: 'Shut down camunda'
          command: 'cd examples/camunda && docker compose down'

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  building-block-test:
    jobs:
      - bb-example-testing
