version: '3'

services:
  mock:
    image: stoplight/prism:4.1.2
    command: mock api/workflow-engine.yml
    volumes:
      - ../../api:/usr/src/prism/packages/cli/api
    ports:
      - '4010:4010'
