version: '3.7'
services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${CADDY_DATA_FOLDER}:/data
      - ${CADDY_CONFIG_FOLDER}:/config

volumes:
  caddy_data:
