---
version: '3.9'
services:
  prism:
    build: .
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/workflow-engine.yml'
    volumes:
      - ../../workflow-engine.yml:/tmp/workflow-engine.yml:ro
    ports:
      # Serve the mocked API locally as available on port 80
      - '80:4010'
      - '443:4010'
