version: '3'
services:
  mockoon:
    image: mockoon/cli:latest
    command: mockoon-cli start  --data <directory> # this is where the change takes place
    networks:
      demo:
    ports:
      - '8001:8001'
    volumes:
      - type: bind
        source: ../../api/swagger.yaml
        target: /www
networks:
  demo:
