version: '3'

services:
  mock:
    build: .
    command: mock api/workflow-engine.yml
    ports:
      - '4010:4010'
  # This was the old attempt, and can be removed when the build works.
  # mock:
  #   image: stoplight/prism:4.1.2
  #   command: mock api/workflow-engine.yml
  #   volumes:
  #     - ./api:/usr/src/prism/packages/cli/api
  #   ports:
  #     - '4010:4010'
