version: "3"
services:
  mockoon:
    image: mockoon/cli:latest
    command: -d /data # this is where the change takes place
    ports:
      - "3000:3000"
    networks:
      demo:
    volumes:
      - type: bind
        source: ../../api/workflow-engine.yml  
        target: /data 
  pytest:
   build:
     context: ../../test/.
   tty: true
   stdin_open: true
   networks:
      demo:
