openapi: 3.0.0
info:
  title: Workflow Building Block API
  description: The GovStack Workflow Building Block API
  contact:
    email: workflow@discourse.govstack.global
  license:
    name: MIT
  version: 1.0.0
tags:
  - name: v1
    description:
      This endpoint is a requirement for the v1 workflow engine BB
      specification.
  - name: admins
    description:
      Endpoints that are available to administrators of this workflow BB
      instance (e.g., to configure the workflow BB.)
  - name: developers
    description:
      Endpoints that are available to other GovStack developers/applications to
      discover, instantiate, and monitor processes.
  - name: Design
    description: Endpoints that are used to configure workflows
  - name: Runtime
    description: Endpoints that are used to execute and monitor workflows
paths:
  /processes:
    get:
      tags:
        - v1
        - developers
        - Design
      summary: returns a list of workflow processes i.e., definitions of process
      description: Listing of all processes with basic information
      operationId: getProcessList
      parameters:
        - name: name
          in: query
          schema:
            type: string
          required: false
          example: Register Child Birth Process
      responses:
        '200':
          description: list of processes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Process'
        '404':
          description: processes not found
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - admins
        - Design
      summary: adds a new process
      description: Adds a process to the system
      operationId: addProcess
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessDefinition'
      responses:
        '201':
          description: Process successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Process'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /processes/{processId}:
    get:
      tags:
        - v1
        - developers
        - Design
      summary: returns detailed information about a process
      description: |
        Pass in the ID of the process and it will return all information about that process
      operationId: getProcess
      parameters:
        - $ref: '#/components/parameters/processIdParam'
      responses:
        '200':
          description: process found and representation returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Process'
        '404':
          description: process not found
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - Design
        - admins
      parameters:
        - $ref: '#/components/parameters/processIdParam'
      summary: updates an existing process
      description: Updates a process on the system
      operationId: updateProcess
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '204':
          description: Process successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Process'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - admins
      parameters:
        - $ref: '#/components/parameters/processIdParam'
      summary: deletes an existing process
      description: Deletes a process on the system
      operationId: deleteProcess
      responses:
        '200':
          description: Process successfully deleted
        '500':
          $ref: '#/components/responses/InternalServerError'
  /processes/{processId}/start:
    post:
      tags:
        - v1
        - developers
        - Runtime
      summary: instantiates a process execution; creates a process instance
      operationId: start
      description:
        Create a process instance and register it with the execution engine
      requestBody:
        description:
          Process instance initiation payload (initial "state" for the process)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessInstancePayload'
      parameters:
        - $ref: '#/components/parameters/processIdParam'
      responses:
        '201':
          description:
            Process started; registered for execution with unique process
            instance ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  instanceId:
                    type: integer
                    description: The unique process instance ID.
        '404':
          description: Invalid processId. Process does not exist
        '500':
          $ref: '#/components/responses/InternalServerError'
  /instances/:
    get:
      tags:
        - v1
        - developers
        - Runtime
      summary:
        returns a list of process instances; can be constrained by processId to
        get instances of specific process type
      description:
        Optionally include a processId in the query params to filter by that
        process
      parameters:
        - $ref: '#/components/parameters/processIdQueryParam'
      responses:
        '200':
          description: An array of process instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessInstance'
        '404':
          description: Invalid instance ID. Process instance does not exist
        '500':
          $ref: '#/components/responses/InternalServerError'
  /instances/{instanceId}:
    get:
      tags:
        - v1
        - developers
        - Runtime
      summary: return execution status details for a single process instance
      description:
        By passing in the process instance ID, get full details on its
        execution, including server logs emitted.
      parameters:
        - name: instanceId
          in: path
          description: Numeric ID of a process instance
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        '200':
          description: A detailed process instance status object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessInstance'
        '404':
          description: Invalid processId. Process does not exist
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ProcessDefinition:
      type: object
      required:
        - name
        - type
        - version
      properties:
        name:
          type: string
          description: name of a process
        type:
          type: string
          enum:
            - None
            - Private
            - Public
        version:
          type: string
        isExecutable:
          type: boolean
          description: Specifies whether the Process is executable
        isClosed:
          type: boolean
          description:
            whether Messages and Events, not modeled in Process, can occur when
            the Process is executed or performed
        description:
          type: string
        processBody:
          $ref: '#/components/schemas/ListOfProperties'
    Process:
      type: object
      properties:
        id:
          type: integer
          description: generated by a system surrogate primary key
        processDefinition:
          $ref: '#/components/schemas/ProcessDefinition'
    ProcessInstancePayload:
      type: object
      required:
        - processStartedBy
      properties:
        processStartedBy:
          type: string
        instanceValues:
          $ref: '#/components/schemas/ListOfProperties'
    ProcessInstance:
      type: object
      properties:
        id:
          type: integer
          description: generated by a system surrogate primary key
        processRef:
          type: integer
          description: reference to the process definition
          example: 4
        initTime:
          type: string
          description: Initiation Timestamp
        state:
          type: string
          description: see BPMN specification v.2.0 section 13.2.2
        lastChangeTime:
          type: string
          description: last change Timestamp
    ListOfProperties:
      type: array
      items:
        type: object
        properties:
          code:
            type: string
          value:
            type: string
  parameters:
    processIdQueryParam:
      in: query
      name: processId
      required: false
      schema:
        type: integer
        minimum: 1
      description: The id for a defined process in the workflow engine.
    processIdParam:
      in: path
      name: processId
      required: true
      schema:
        type: integer
        minimum: 1
      description: The id for a defined process in the workflow engine.
  responses:
    InternalServerError:
      description: Internal server error, please contact administrator
