name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: ngeor/swagger-to-diagram
    steps:
    - uses: actions/checkout@v3
    - name: Create a UML diagram
      run: swagger2png.sh ./src/main/yaml-api/swagger.yaml diagram.png
